#pragma config(Sensor, S1,     soundSensor,    sensorSoundDBA)
#pragma config(Sensor, S2,     lightSensor,    sensorLightInactive)
#pragma config(Sensor, S3,     sonarSensor,    sensorSONAR)
#pragma config(Sensor, S4,     touchSensor,    sensorTouch)
#pragma config(Motor,  motorA,          rightMotor,    tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorC,          leftMotor,     tmotorNXT, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
    SensorType[lightSensor] = sensorLightActive;
    while (true)
    {
        nxtDisplayTextLine(1, "Sound=%d", SensorValue[soundSensor]);
        nxtDisplayTextLine(2, "Light=%d", SensorValue[lightSensor]);
        nxtDisplayTextLine(3, "Sonar=%d", SensorValue[sonarSensor]);
        nxtDisplayTextLine(4, "Touch=%d", SensorValue[touchSensor]);
        wait1Msec(100);
    }
}
