#pragma config(Sensor, S1,     soundSensor,    sensorSoundDBA)
#pragma config(Sensor, S2,     lightSensor,    sensorLightInactive)
#pragma config(Sensor, S3,     sonarSensor,    sensorSONAR)
#pragma config(Sensor, S4,     touchSensor,    sensorTouch)
#pragma config(Motor,  motorA,          rightMotor,    tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorC,          leftMotor,     tmotorNXT, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define SOUND_THRESHOLD 40

task main()
{
    int prevSoundLevel;
    int currSoundLevel;
    bool bOn = false;

    prevSoundLevel = SensorValue[soundSensor];
    while (true)
    {
        currSoundLevel = SensorValue[soundSensor];
        if ((prevSoundLevel < SOUND_THRESHOLD) &&
            (currSoundLevel > SOUND_THRESHOLD))
        {
            bOn = !bOn;
        }
        prevSoundLevel = currSoundLevel;
        nxtDisplayTextLine(1, "Sound=%d", currSoundLevel);
        nxtDisplayTextLine(2, "Status=%d", bOn);

        if (!bOn)
        {
            motor[leftMotor] = 0;
            motor[rightMotor] = 0;
        }
        else
        {
            motor[leftMotor] = 30;
            motor[rightMotor] = 30;
        }

        wait1Msec(10);
    }
}
