#pragma config(Sensor, S1,     soundSensor,    sensorSoundDBA)
#pragma config(Sensor, S2,     lightSensor,    sensorLightInactive)
#pragma config(Sensor, S3,     sonarSensor,    sensorSONAR)
#pragma config(Sensor, S4,     touchSensor,    sensorTouch)
#pragma config(Motor,  motorA,          rightMotor,    tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorC,          leftMotor,     tmotorNXT, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define DARK_VALUE      40
#define LIGHT_VALUE     65

task main()
{
    int lightThreshold = (DARK_VALUE + LIGHT_VALUE)/2;
    SensorType[lightSensor] = sensorLightActive;
    while (true)
    {
        if (SensorValue[lightSensor] > lightThreshold)
        {
            motor[leftMotor] = 25;
            motor[rightMotor] = 10;
        }
        else if (SensorValue[lightSensor] < lightThreshold)
        {
            motor[leftMotor] = 10;
            motor[rightMotor] = 25;
        }
        else
        {
            motor[leftMotor] = 30;
            motor[rightMotor] = 30;
        }

        wait1Msec(100);
    }
}
