#pragma config(Sensor, S1,     soundSensor,    sensorSoundDBA)
#pragma config(Sensor, S2,     lightSensor,    sensorLightInactive)
#pragma config(Sensor, S3,     sonarSensor,    sensorSONAR)
#pragma config(Sensor, S4,     touchSensor,    sensorTouch)
#pragma config(Motor,  motorA,          rightMotor,    tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorC,          leftMotor,     tmotorNXT, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define DARK_THRESHOLD      40
#define LIGHT_THRESHOLD     65
#define SONAR_DISTANCE      20

#define DRIVE_POWER         25
#define KP                  0.8

task main()
{
    int lightThreshold = (LIGHT_THRESHOLD + DARK_THRESHOLD)/2;
    bool fOn = false;
    int prevTouchValue = 0;
    int currTouchValue = 0;

    SensorType[lightSensor] = sensorLightActive;
    while (true)
    {
        nxtDisplayTextLine(1, "Sound=%d", SensorValue[soundSensor]);
        nxtDisplayTextLine(2, "Light=%d", SensorValue[lightSensor]);
        nxtDisplayTextLine(3, "Sonar=%d", SensorValue[sonarSensor]);
        nxtDisplayTextLine(4, "Touch=%d", SensorValue[touchSensor]);

        currTouchValue = SensorValue[touchSensor];
        if (currTouchValue != prevTouchValue)
        {
            if (currTouchValue == 1)
            {
                fOn = !fOn;
            }
            prevTouchValue = currTouchValue;
        }

        if (!fOn || (SensorValue[sonarSensor] < SONAR_DISTANCE))
        {
            motor[leftMotor] = 0;
            motor[rightMotor] = 0;
        }
        else
        {
            int error = SensorValue[lightSensor] - lightThreshold;

            motor[leftMotor] = DRIVE_POWER + KP*error;
            motor[rightMotor] = DRIVE_POWER - KP*error;
        }

        wait1Msec(10);
    }
}
