#pragma config(Sensor, S1,     soundSensor,    sensorSoundDBA)
#pragma config(Sensor, S2,     lightSensor,    sensorLightInactive)
#pragma config(Sensor, S3,     sonarSensor,    sensorSONAR)
#pragma config(Sensor, S4,     touchSensor,    sensorTouch)
#pragma config(Motor,  motorA,          rightMotor,    tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorC,          leftMotor,     tmotorNXT, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define CLICKS_PER_INCH         52.5
#define TARGET_DISTANCE         24.0

task main()
{
    nMotorEncoder[leftMotor] = 0;
    nMotorEncoder[rightMotor] = 0;

    nxtDisplayTextLine(0, "Target=%d", TARGET_DISTANCE*CLICKS_PER_INCH);
    while ((nMotorEncoder[leftMotor] + nMotorEncoder[rightMotor])/2 <
           TARGET_DISTANCE*CLICKS_PER_INCH)
    {
        motor[leftMotor] = 30;
        motor[rightMotor] = 30;
        wait1Msec(10);
        nxtDisplayTextLine(1, "LEncoder=%d", nMotorEncoder[leftMotor]);
        nxtDisplayTextLine(2, "REncoder=%d", nMotorEncoder[rightMotor]);
    }
    motor[leftMotor] = 0;
    motor[rightMotor] = 0;

    while (true)
    {
        wait1Msec(1000);
    }
}
