#pragma config(Sensor, S1,     soundSensor,    sensorSoundDBA)
#pragma config(Sensor, S2,     lightSensor,    sensorLightInactive)
#pragma config(Sensor, S3,     sonarSensor,    sensorSONAR)
#pragma config(Sensor, S4,     touchSensor,    sensorTouch)
#pragma config(Motor,  motorA,          rightMotor,    tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorC,          leftMotor,     tmotorNXT, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define CLICKS_PER_INCH         52.5
#define CLICKS_PER_DEGREE       3.42

void Drive(float distance, int power)
{
    int targetClicks = abs(distance)*CLICKS_PER_INCH;

    nxtDisplayTextLine(0, "Target=%d", targetClicks);
    power = abs(power);
    if (distance < 0.0)
    {
        power = -power;
    }

    nMotorEncoder[leftMotor] = 0;
    nMotorEncoder[rightMotor] = 0;
    while (abs(nMotorEncoder[leftMotor] + nMotorEncoder[rightMotor])/2 < targetClicks)
    {
        motor[leftMotor] = power;
        motor[rightMotor] = power;
        wait1Msec(10);
        nxtDisplayTextLine(1, "LEncoder=%d", nMotorEncoder[leftMotor]);
        nxtDisplayTextLine(2, "REncoder=%d", nMotorEncoder[rightMotor]);
    }
    motor[leftMotor] = 0;
    motor[rightMotor] = 0;
}   //Drive

void Turn(float angle, int power)
{
    int targetClicks = abs(angle)*CLICKS_PER_DEGREE;

    nxtDisplayTextLine(0, "Target=%d", targetClicks);
    power = abs(power);
    if (angle < 0.0)
    {
        power = -power;
    }

    nMotorEncoder[leftMotor] = 0;
    nMotorEncoder[rightMotor] = 0;
    while (abs(nMotorEncoder[leftMotor] - nMotorEncoder[rightMotor]) < targetClicks)
    {
        motor[leftMotor] = power;
        motor[rightMotor] = -power;
        wait1Msec(10);
        nxtDisplayTextLine(1, "LEncoder=%d", nMotorEncoder[leftMotor]);
        nxtDisplayTextLine(2, "REncoder=%d", nMotorEncoder[rightMotor]);
    }
    motor[leftMotor] = 0;
    motor[rightMotor] = 0;
}   //Turn

task main()
{
    Drive(24.0, 20);
    Turn(180.0, 20);
    Drive(24.0, 20);
    while (true)
    {
        wait1Msec(1000);
    }
}
