#pragma config(Sensor, S1,     soundSensor,    sensorSoundDBA)
#pragma config(Sensor, S2,     lightSensor,    sensorLightInactive)
#pragma config(Sensor, S3,     sonarSensor,    sensorSONAR)
#pragma config(Sensor, S4,     touchSensor,    sensorTouch)
#pragma config(Motor,  motorA,          rightMotor,    tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorC,          leftMotor,     tmotorNXT, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define CLICKS_PER_INCH         53.6
#define CLICKS_PER_DEGREE       3.42
#define DRIVE_KP                18.0
#define TURN_KP                 1.0
#define DRIVE_TOLERANCE         0.5
#define TURN_TOLERANCE          0.5

void Drive(float distance)
{
    nxtDisplayTextLine(0, "Distance=%6.1f", distance);
    nMotorEncoder[leftMotor] = 0;
    nMotorEncoder[rightMotor] = 0;
    while (true)
    {
        float leftPos = nMotorEncoder[leftMotor]/CLICKS_PER_INCH;
        float rightPos = nMotorEncoder[rightMotor]/CLICKS_PER_INCH;
        nxtDisplayTextLine(1, "LPos=%6.1f", leftPos);
        nxtDisplayTextLine(2, "RPos=%6.1f", rightPos);
        if (abs(distance - (leftPos + rightPos)/2.0) <= DRIVE_TOLERANCE)
        {
            motor[leftMotor] = 0;
            motor[rightMotor] = 0;
            nxtDisplayTextLine(7, "Done!");
            break;
        }
        motor[leftMotor] = DRIVE_KP*(distance - leftPos);
        motor[rightMotor] = DRIVE_KP*(distance - rightPos);
    }
}   //Drive

void Turn(float angle)
{
    nxtDisplayTextLine(0, "Angle=%6.1f", angle);
    nMotorEncoder[leftMotor] = 0;
    nMotorEncoder[rightMotor] = 0;
    while (true)
    {
        float currAngle = (nMotorEncoder[leftMotor] - nMotorEncoder[rightMotor])/
                          CLICKS_PER_DEGREE;
        nxtDisplayTextLine(1, "CurrAngle=%6.1f", currAngle);
        if (abs(angle - currAngle) <= TURN_TOLERANCE)
        {
            motor[leftMotor] = 0;
            motor[rightMotor] = 0;
            nxtDisplayTextLine(7, "Done!");
            break;
        }
        int motorPower = TURN_KP*(angle - currAngle);
        motor[leftMotor] = motorPower;
        motor[rightMotor] = -motorPower;
    }
}   //Turn

task main()
{
    Drive(24.0);
    Turn(180.0);
    Drive(24.0);
    while (true)
    {
        wait1Msec(1000);
    }
}
