#pragma config(Sensor, S1,     soundSensor,    sensorSoundDBA)
#pragma config(Sensor, S2,     lightSensor,    sensorLightInactive)
#pragma config(Sensor, S3,     sonarSensor,    sensorSONAR)
#pragma config(Sensor, S4,     touchSensor,    sensorTouch)
#pragma config(Motor,  motorA,          rightMotor,    tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorC,          leftMotor,     tmotorNXT, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"

#define DEAD_BAND               20

task main()
{
    int x, y;

    while (true)
    {
        getJoystickSettings(joystick);

        x = joystick.joy1_x1;
        y = joystick.joy1_y1;

        if (abs(x) < DEAD_BAND)
        {
            x = 0;
        }

        if (abs(y) < DEAD_BAND)
        {
            y = 0;
        }

        motor[leftMotor] = (y + x)/2;
        motor[rightMotor] = (y - x)/2;

        EndTimeSlice();
    }
}
