#pragma config(Sensor, S1,     soundSensor,    sensorSoundDBA)
#pragma config(Sensor, S2,     lightSensor,    sensorLightInactive)
#pragma config(Sensor, S3,     sonarSensor,    sensorSONAR)
#pragma config(Sensor, S4,     touchSensor,    sensorTouch)
#pragma config(Motor,  motorA,          rightMotor,    tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorC,          leftMotor,     tmotorNXT, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"
#include "..\ftclib\trcdefs.h"
#include "..\ftclib\dbgtrace.h"
#include "..\ftclib\joystick.h"
#include "..\ftclib\drive.h"
#include "..\ftclib\sm.h"
#include "..\ftclib\song.h"

#define BAR_DURATION                    2800

char    g_Segment1[] =
    "A4.8+,G4.16,"
    "F4.8+,G4.16,A4.8+,Bb4.16,C5.4,A4.12,G4.12,F4.12,"
    "E4.8+,D4.16,E4.8+,F4.16,C4.4,D4.12,C4.12,Bb3.12,"
    "A3.8+,C4.16,F4.8+,A4.16,G4.8+,F#4.16,G4.8+,D4.16,"
    "F4.8+,E4.16,E4.8+,F4.16,G4.4,A4.8+,G4.16";
char    g_Segment2[] =
    "F4.8+,G4.16,A4.8+,Bb4.16,C5.4,A4.12,G4.12,F4.12,"
    "E4.8+,D4.16,E4.8+,F4.16,C4.4,D4.12,C4.12,Bb3.12,"
    "A3.8+,C4.16,F4.8+,A4.16,G4.12,F#4.12,G4.12,Bb4.8+,E4.16,"
    "F4.4,R.2,E4.8+,E4.16";

char    g_Segment3[] =
    "A4.8+,G#4.16,A4.8+,B4.16,C5.8+,B4.16,A4.8+,C5.16,"
    "B4.8+,A4.16,G4.8+,A4.16,B4.4,R.12,B4.12,C5.12,"
    "D5.8+,C5.16,B4.8+,C5.16,D5.8+,C5.16,B4.8+,D5.16,"
    "C5.8+,B4.16,A4.8+,B4.16,C5.4,R.8+,A4.16";
char    g_Segment4[] =
    "C5.12,B4.12,A4.12,C5.12,B4.12,A4.12,C5.12,B4.12,A4.12,C5.12,B4.12,C5.12,"
    "D5.2,R.4,E5.8+,D5.16,"
    "C5.8+,D5.16,E5.8+,F5.16,G5.4,E5.12,D5.12,C5.12,"
    "B4.8+,A4.16,B4.8+,C5.16,G4.4,A4.12,G4.12,F4.12";
char    g_Segment5[] =
    "E4.8+,G4.16,C5.8+,E5.16,D5.8+,C#5.16,D5.8+,A4.16,"
    "C5.8+,B4.16,B4.8+,C5.16,D5.4,E5.8+,D5.16,"
    "C5.8+,D5.16,E5.8+,F5.16,G5.4,E5.12,D5.12,C5.12,"
    "B4.8+,A4.16,B4.8+,C5.16,G4.4,A4.12,G4.12,F4.12";

char    g_Segment6[] =
    "E4.8+,G4.16,C5.8+,E5.16,D5.12,C#5.12,D5.12,F5.8+,B4.16,"
    "C5.4,R.2,E4.8+,E4.16";

char    g_Segment7[] =
    "E4.8+,G4.16,C5.8+,E5.16,D5.12,C#5.12,D5.12,F5.8+,B4.16,"
    "C5.4,R.2.4";

char   *g_SongSegments[] =
{
    g_Segment1,
    g_Segment2,
    g_Segment3,
    g_Segment4,
    g_Segment5,
    g_Segment6,
    g_Segment3,
    g_Segment4,
    g_Segment5,
    g_Segment7,
    NULL
};

JOYSTICK    g_Joystick;
DRIVE       g_Drive;
SONG        g_LesMiserable;
bool        g_fSongOn = false;

void JoyBtnEvent(int joystickID, int eventType, int eventID, bool fPressed)
{
    if (joystickID == 1)
    {
        if (eventType == JOYEVENT_BUTTON)
        {
            nxtDisplayTextLine(2, "Btn=%d,Press=%d", eventID, fPressed);
            switch (eventID)
            {
                case Xbox_A:
                    if (fPressed)
                    {
                        g_fSongOn = !g_fSongOn;
                    }

                    if (g_fSongOn)
                    {
                        SongResume(g_LesMiserable);
                    }
                    else
                    {
                        SongStop(g_LesMiserable);
                    }
                    break;
            }
        }
        else if (eventType == JOYEVENT_TOPHAT)
        {
            switch (eventID)
            {
                case TopHat_Up:
                    break;
            }
        }
    }
}   //JoyBtnEvent

void RobotInit()
{
    JoystickInit(g_Joystick, 1);
    DriveInit(g_Drive, leftMotor, rightMotor);
    SongInit(g_LesMiserable, &g_SongSegments[0]);
    SongStart(g_LesMiserable, BAR_DURATION, SONGO_REPEAT, true);
}   //RobotInit

void HiFreqTasks()
{
    SongTask(g_LesMiserable);
}   //HiFreqTasks

void InputTasks()
{
    getJoystickSettings(joystick);
    JoystickTask(g_Joystick);
}   //InputTasks

void MainTasks()
{
    int drivePower = JoystickGetY1WithDeadband(g_Joystick, true);
    int turnPower = JoystickGetX1WithDeadband(g_Joystick, true);
    nxtDisplayTextLine(0, "Arcade: %d,%d", drivePower, turnPower);
    DriveArcade(g_Drive, drivePower, turnPower);
}   //MainTasks

void OutputTasks()
{
    DriveTask(g_Drive);
}   //OutputTasks

task main()
{
    unsigned long nextPeriod;

    RobotInit();
    nextPeriod = nPgmTime;
    while (true)
    {
        HiFreqTasks();
        if (nPgmTime >= nextPeriod)
        {
            nextPeriod += LOOP_PERIOD;
            InputTasks();
            MainTasks();
            OutputTasks();
        }
        EndTimeSlice();
    }
}   //main
