#pragma config(Sensor, S1,     soundSensor,    sensorSoundDBA)
#pragma config(Sensor, S2,     lightSensor,    sensorLightInactive)
#pragma config(Sensor, S3,     sonarSensor,    sensorSONAR)
#pragma config(Sensor, S4,     touchSensor,    sensorTouch)
#pragma config(Motor,  motorA,          rightMotor,    tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorC,          leftMotor,     tmotorNXT, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "..\ftclib\trcdefs.h"
#include "..\ftclib\dbgtrace.h"
#include "..\ftclib\sm.h"
#include "..\ftclib\touch.h"
#include "..\ftclib\drive.h"
#include "..\ftclib\song.h"

#define DRIVE_POWER                     25
#define KP                              0.8

#define BLACK_THRESHOLD                 40
#define WHITE_THRESHOLD                 65
#define LIGHT_THRESHOLD                 ((BLACK_THRESHOLD + WHITE_THRESHOLD)/2)
#define SONAR_DISTANCE                  20

#define BAR_DURATION                    2800

char    g_Segment1[] =
    "A4.8+,G4.16,"
    "F4.8+,G4.16,A4.8+,Bb4.16,C5.4,A4.12,G4.12,F4.12,"
    "E4.8+,D4.16,E4.8+,F4.16,C4.4,D4.12,C4.12,Bb3.12,"
    "A3.8+,C4.16,F4.8+,A4.16,G4.8+,F#4.16,G4.8+,D4.16,"
    "F4.8+,E4.16,E4.8+,F4.16,G4.4,A4.8+,G4.16";
char    g_Segment2[] =
    "F4.8+,G4.16,A4.8+,Bb4.16,C5.4,A4.12,G4.12,F4.12,"
    "E4.8+,D4.16,E4.8+,F4.16,C4.4,D4.12,C4.12,Bb3.12,"
    "A3.8+,C4.16,F4.8+,A4.16,G4.12,F#4.12,G4.12,Bb4.8+,E4.16,"
    "F4.4,R.2,E4.8+,E4.16";

char    g_Segment3[] =
    "A4.8+,G#4.16,A4.8+,B4.16,C5.8+,B4.16,A4.8+,C5.16,"
    "B4.8+,A4.16,G4.8+,A4.16,B4.4,R.12,B4.12,C5.12,"
    "D5.8+,C5.16,B4.8+,C5.16,D5.8+,C5.16,B4.8+,D5.16,"
    "C5.8+,B4.16,A4.8+,B4.16,C5.4,R.8+,A4.16";
char    g_Segment4[] =
    "C5.12,B4.12,A4.12,C5.12,B4.12,A4.12,C5.12,B4.12,A4.12,C5.12,B4.12,C5.12,"
    "D5.2,R.4,E5.8+,D5.16,"
    "C5.8+,D5.16,E5.8+,F5.16,G5.4,E5.12,D5.12,C5.12,"
    "B4.8+,A4.16,B4.8+,C5.16,G4.4,A4.12,G4.12,F4.12";
char    g_Segment5[] =
    "E4.8+,G4.16,C5.8+,E5.16,D5.8+,C#5.16,D5.8+,A4.16,"
    "C5.8+,B4.16,B4.8+,C5.16,D5.4,E5.8+,D5.16,"
    "C5.8+,D5.16,E5.8+,F5.16,G5.4,E5.12,D5.12,C5.12,"
    "B4.8+,A4.16,B4.8+,C5.16,G4.4,A4.12,G4.12,F4.12";

char    g_Segment6[] =
    "E4.8+,G4.16,C5.8+,E5.16,D5.12,C#5.12,D5.12,F5.8+,B4.16,"
    "C5.4,R.2,E4.8+,E4.16";

char    g_Segment7[] =
    "E4.8+,G4.16,C5.8+,E5.16,D5.12,C#5.12,D5.12,F5.8+,B4.16,"
    "C5.4,R.2.4";

char   *g_SongSegments[] =
{
    g_Segment1,
    g_Segment2,
    g_Segment3,
    g_Segment4,
    g_Segment5,
    g_Segment6,
    g_Segment3,
    g_Segment4,
    g_Segment5,
    g_Segment7,
    NULL
};

TOUCH       g_Touch;
DRIVE       g_Drive;
SONG        g_LesMiserable;
bool        g_fRobotOn = false;

void TouchEvent(TOUCH &touch, bool fActive)
{
    if (fActive)
    {
        g_fRobotOn = !g_fRobotOn;
        if (g_fRobotOn)
        {
            SongResume(g_LesMiserable);
            //
            // Turn light sensor ON.
            //
            SensorType[lightSensor] = sensorLightActive;
        }
        else
        {
            SongStop(g_LesMiserable);
            //
            // Turn light sensor OFF.
            //
            SensorType[lightSensor] = sensorLightInactive;
        }
    }
}   //TouchEvent

void RobotInit()
{
    TouchInit(g_Touch, touchSensor);
    DriveInit(g_Drive, leftMotor, rightMotor);
    SongInit(g_LesMiserable, &g_SongSegments[0]);
    SongStart(g_LesMiserable, BAR_DURATION, SONGO_REPEAT, true);
}   //RobotInit

void HiFreqTasks()
{
    SongTask(g_LesMiserable);
}   //HiFreqTasks

void InputTasks()
{
    TouchTask(g_Touch);
}   //InputTasks

void MainTasks()
{
    if (!g_fRobotOn || (SensorValue[sonarSensor] < SONAR_DISTANCE))
    {
        DriveArcade(g_Drive, 0, 0);
    }
    else
    {
        DriveArcade(g_Drive,
                    DRIVE_POWER,
                    (int)(KP*(SensorValue[lightSensor] - LIGHT_THRESHOLD)));
    }
}   //MainTasks

void OutputTasks()
{
    DriveTask(g_Drive);
}   //OutputTasks

task main()
{
    unsigned long nextPeriod;

    RobotInit();
    nextPeriod = nPgmTime;
    while (true)
    {
        HiFreqTasks();
        if (nPgmTime >= nextPeriod)
        {
            nextPeriod += LOOP_PERIOD;
            InputTasks();
            MainTasks();
            OutputTasks();
        }
        EndTimeSlice();
    }
}   //main
